import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { syncCurrentUserToDb } from "@/lib/syncUserToDb";


const inter = Inter({ subsets: ["latin"] });
const popins=Poppins({
  subsets: ["latin"],
  variable: "--font-popins",
  weight:["100","200","300","400","500","600","700","800","900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
const clerkFrontendApi =
  process.env.NEXT_PUBLIC_CLERK_FRONTEND_API ??
  process.env.CLERK_FRONTEND_API;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await syncCurrentUserToDb();

  return (
    <html lang="en">
      <ClerkProvider
        publishableKey={clerkPublishableKey}
        signInUrl="/sign-in"
        signUpUrl="/sign-up"
        afterSignOutUrl="/"
      >
        <body className="bg-slate-50 min-h-screen">{children}</body>
      </ClerkProvider>
    </html>
  );
}