import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google"; 
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });
const popins=Poppins({
  subsets: ["latin"],
  variable: "--font-popins",
  weight:["100","200","300","400","500","600","700","800","900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body className="bg-slate-50 min-h-screen">
        <main>{children}</main>
      </body>
      </ClerkProvider>
    </html>
  );
}